language: cpp
before_script:
- sudo apt-get update -qq 
- sudo apt-get install libgtest-dev -y
- sudo cmake /usr/src/gtest/CMakeLists.txt
- sudo make /usr/src/gtest/
- sudo cp /usr/src/gtest/*.a /usr/lib
- sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
- sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T second-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uneogen12:$BINTRAY_API_KEY "https://api.bintray.com/content/neogen12/First/first12/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
